### ISSUE TITLE
LBR ROS 2 control controllers

### ISSUE THREAD

**Issue by Enzo-let** [lbr-stack/lbr_fri_ros2_stack#282]
```
# LBR ROS 2 control controllers
/**/lbr_joint_position_command_controller:
  ros__parameters:
    robot_name: lbr

/**/lbr_torque_command_controller:
  ros__parameters:
    robot_name: lbr

/**/lbr_wrench_command_controller:
  ros__parameters:
    robot_name: lbr
```
Wish you happy. I have a question about if i can use these controllers to control the hardware.
